#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn version --no-commit-hooks --no-git-tag-version --patch
git add package.json
git commit --no-verify -m "chore: bump version"
git push origin HEAD
```